events {}

http {

resolver 127.0.0.11 valid=30s;

include       /etc/nginx/mime.types;
default_type  application/octet-stream;

upstream task_backend {
    least_conn;
    server flask1:8000;
    server flask2:8000;
}

server {
    listen 80;
    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    location / {
        proxy_pass http://task_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /static/;
    }

}

}